experiment_name: single_embedding_prediction
vocab_file: bert-base-uncased-vocab.txt
char_to_idx_file: char_to_idx_map.pt
embedding_file: distilbert_embedding_matrix.pt
word_length: 18
hyperparameters:
  embedding_noise:
    - .25
  word_length:
    - 18
  char_vocab_size:
    - 70
  char_embedding_size:
    - 8
  conv_activation:
    - 'relu'
  conv.kernel|filter_sizes:
    -
      - [1,768]
      - [1,2048]  
      - [1,2048]  
  token_embedding_size:
    - 768
  batch_size:
    - 512
  learning_rate:
    - 0.0001
  loss_fn:
    - 'xent'
  optimizer:
    - 'adam'
  epochs:
    - 50
  lr_step_size:
    - 190700
  lr_decay:
    - 1
  learning_rate_cap:
    - 20
  run_validation:
     - True
  random_seed:
    - 3
  model_size_range_bytes:
    - [0, 1.1e+8]
  model_checkpoint:
    - models/db5b7cbd3
  
