experiment_name: single_word_prediction
vocab_file: bert-base-uncased-vocab.txt
char_to_idx_file: char_to_idx_map.pt
embedding_file: distilbert_embedding_matrix.pt
word_length: 12
hyperparameters:
  misspelling_rate:
    - 0
  misspelling_transforms:
    - null  
  word_length:
    - 12
  char_embedding_size:
    - 8
  conv_activation:
    - 'relu'
  seg1_type:
    - 'unfold'
  seg1.kernel_size:
    - 12
  seg2.kernel|filter_sizes:
    -
      - [1,768]
  token_embedding_size:
    - 768
  batch_size:
    - 256
  learning_rate:
    - .0001
  loss_fn:
    - 'xent'
  eval_acc:
    - True
  optimizer:
    - 'adam'
  epochs:
    - 100
  space_freq:
    - 1
  lr_step_size:
    - 190700
  lr_decay:
    - 1
  learning_rate_cap:
    - 20
  run_validation:
     - True
  random_seed:
    - 3
  model_size_range_bytes:
    - [0, 9.0e+8]
  end_of_word_loss_weight:
    - 0.0
  add_random_count:
    - 0
