experiment_name: testing_bert_charcloze_to_dense_tok
dataset: 'imdb_tok96_char_encoded384charidx2.pt'
dataset_split: [.3, .06]
input_type: char_masked
output_type: only_masked
token_seq_length: 96
num_masks: 6
hyperparameters:
  input_type: char_masked
  output_type: only_masked
  token_seq_length: 96
  char_vocab_size: [70]
  char_embedding_size: [8]
  conv_activation:
    - 'relu'
  seg1_type:
    - 'unfold'
  seg1.kernel_size:
    - 18
  seg2.kernel|filter_sizes:
    -
      - [1,2048]
      - [1,2048]
      - [1,2048]
      - [1,2048]
  token_embedding_size:
    - 768
  switchboard_type:
    - rule_based
  sb.sigmoid:
    - hard
  num_masks: 6
  batch_size:
    - 64
  learning_rate:
    - .0001
  loss_fn:
    - 'xentropy'
  optimizer:
    - 'adam'  
  epochs:
    - 1
  lr_step_size:
    - 1000
  run_validation:
     - True
  seed:
    - 0
  bert_checkpoint:
    - bert_distil_dense_out
  skip_bert:
    - False
  position_embeddings:
    - True
  manual_attention:
    - True
  space_loss_weight:
    - 0
  freeze_modules:
    - [bert.transformer.layer.1,
       bert.transformer.layer.2,
       bert.transformer.layer.3,
       bert.transformer.layer.4,
       bert.transformer.layer.5]
  model_checkpoint:
    - models/d3aa9f852
