experiment_name: token_start_pos_prediction
dataset_file: imdb_tok96_char384_enc_no_tok.pt
dataset_split: [.9, .06]
hyperparameters:
  word_length:
    - 18
  char_vocab_size:
    - 70
  char_embedding_size:
    - 8
  conv_activation:
    - 'relu'
  conv.kernel|filter_sizes:
    -
      - [6,256]
      - [5,128]  
      - [4,128]  
      - [1,1]  
  batch_size:
    - 128
  learning_rate:
    - .001
  loss_fn:
    - 'bce'
  optimizer:
    - 'adam'
  epochs:
    - 2
  lr_step_size:
    - 190700
  lr_decay:
    - 1
  learning_rate_cap:
    - 20
  run_validation:
     - True
  random_seed:
    - 3
  model_size_range_bytes:
    - [0, 1.1e+8]
  model_checkpoint:
    - models/743a85523

