experiment_name: single_embedding_prediction
vocab_file: bert-base-uncased-vocab-modmask.txt
char_to_idx_file: char_to_idx_map2.pt
embedding_file: distilbert_embedding_matrix.pt
word_length: 18
hyperparameters:
  word_length:
    - 18
  char_vocab_size:
    - 70
  char_embedding_size:
    - 8
  conv_activation:
    - 'relu'
  seg1_type:
    - 'unfold'
  seg1.kernel_size:
    - 18
  seg2.kernel|filter_sizes:
    -
      - [1,2048]
      - [1,2048]  
      - [1,2048]  
      - [1,2048]  
  token_embedding_size:
    - 768
  batch_size:
    - 256
  learning_rate:
    - .00001
  loss_fn:
    - 'vmf_simplified_neg_sample_reg1'
  dot_loss_weight:
    - .00
  eval_acc:
    - True
  optimizer:
    - 'adam'
  epochs:
    - 100
  space_freq:
    - .5
  lr_step_size:
    - 190700
  lr_decay:
    - 1
  learning_rate_cap:
    - 20
  run_validation:
     - True
  random_seed:
    - 8
  model_size_range_bytes:
    - [0, 1.1e+8]
  end_of_word_loss_weight:
    - 0.0
  add_random_count:
    - 4
  misspelling_rate:
    - 0
  misspelling_transforms:
    - 0
